version: '{build}'

branches:
  only:
  - master
  - develop
  - release

clone_depth: 50

init:
  - cmd: git config --global core.autocrlf true
  - cmd: mvn --version

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk10

install:
    # set environment variables "AUTOMATALIB_FORK" and "AUTOMATALIB_BRANCH" to build custom AutomataLib versions.
    # Defaults are "LearnLib" and the current/targeted LearnLib branch (%APPVEYOR_REPO_BRANCH%, relies on the same
    # naming conventions between AutomataLib and LearnLib branches).
  - IF DEFINED AUTOMATALIB_BRANCH (SET AL_BRANCH=%AUTOMATALIB_BRANCH%) ELSE (SET AL_BRANCH=%APPVEYOR_REPO_BRANCH%)
  - IF DEFINED AUTOMATALIB_FORK (SET AL_FORK=%AUTOMATALIB_FORK%) ELSE (SET AL_FORK=LearnLib)
  - cmd: git clone -b %AL_BRANCH% --single-branch https://github.com/%AL_FORK%/automatalib.git automatalib-checkout
  - cmd: cd automatalib-checkout
  - cmd: mvn install -DskipTests
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

cache:
  - C:\Users\appveyor\.m2\

build_script:
  - cmd: mvn install -B -Pintegration-tests

test: off

deploy: off